// Mocks generated by Mockito 5.4.6 from annotations
// in learning_assistant/test/features/comics/domain/usecases/comic_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:learning_assistant/core/error/failures.dart' as _i5;
import 'package:learning_assistant/features/comics/domain/entities/comic_entity.dart'
    as _i6;
import 'package:learning_assistant/features/comics/domain/repositories/comic_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ComicRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockComicRepository extends _i1.Mock implements _i3.ComicRepository {
  MockComicRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>> getComic({
    required int? comicNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComic, [], {#comicNum: comicNum}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>>.value(
              _FakeEither_0<_i5.Failure, _i6.Comic>(
                this,
                Invocation.method(#getComic, [], {#comicNum: comicNum}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comic>>> getComicList() =>
      (super.noSuchMethod(
            Invocation.method(#getComicList, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comic>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Comic>>(
                    this,
                    Invocation.method(#getComicList, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> saveComic({
    required int? comicNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveComic, [], {#comicNum: comicNum}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#saveComic, [], {#comicNum: comicNum}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> deleteComic({
    required int? comicNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComic, [], {#comicNum: comicNum}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#deleteComic, [], {#comicNum: comicNum}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comic>>> loadSavedComics() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedComics, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comic>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Comic>>(
                    this,
                    Invocation.method(#loadSavedComics, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Comic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>> searchComicbyNum({
    required int? comicNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchComicbyNum, [], {#comicNum: comicNum}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>>.value(
              _FakeEither_0<_i5.Failure, _i6.Comic>(
                this,
                Invocation.method(#searchComicbyNum, [], {#comicNum: comicNum}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>> searchComicbyText({
    required String? text,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchComicbyText, [], {#text: text}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>>.value(
              _FakeEither_0<_i5.Failure, _i6.Comic>(
                this,
                Invocation.method(#searchComicbyText, [], {#text: text}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Comic>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> shareComic({
    required int? comicNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareComic, [], {#comicNum: comicNum}),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#shareComic, [], {#comicNum: comicNum}),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> getComicDetails({
    required int? comicNum,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComicDetails, [], {#comicNum: comicNum}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#getComicDetails, [], {
                      #comicNum: comicNum,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getComicExplanation({
    required int? comicNum,
    required String? title,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComicExplanation, [], {
              #comicNum: comicNum,
              #title: title,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#getComicExplanation, [], {
                  #comicNum: comicNum,
                  #title: title,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
