// Mocks generated by Mockito 5.4.6 from annotations
// in learning_assistant/test/features/comics/data/local_data_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:learning_assistant/features/comics/data/datasources/comic_local_data_source.dart'
    as _i3;
import 'package:learning_assistant/features/comics/data/models/comic_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeComicModel_0 extends _i1.SmartFake implements _i2.ComicModel {
  _FakeComicModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ComicLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockComicLocalDataSource extends _i1.Mock
    implements _i3.ComicLocalDataSource {
  MockComicLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveComic({required _i2.ComicModel? comic}) =>
      (super.noSuchMethod(
            Invocation.method(#saveComic, [], {#comic: comic}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ComicModel> loadSavedComic({required int? num}) =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedComic, [], {#num: num}),
            returnValue: _i4.Future<_i2.ComicModel>.value(
              _FakeComicModel_0(
                this,
                Invocation.method(#loadSavedComic, [], {#num: num}),
              ),
            ),
          )
          as _i4.Future<_i2.ComicModel>);

  @override
  _i4.Future<void> deleteSavedComic({required int? num}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedComic, [], {#num: num}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.ComicModel>> loadSavedComics() =>
      (super.noSuchMethod(
            Invocation.method(#loadSavedComics, []),
            returnValue: _i4.Future<List<_i2.ComicModel>>.value(
              <_i2.ComicModel>[],
            ),
          )
          as _i4.Future<List<_i2.ComicModel>>);

  @override
  _i4.Future<void> deleteSavedComics() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSavedComics, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
