// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0CBkl1pweSjq-wfSzudYazH84o0vnS6k',
    appId: '1:134055692731:web:c46bee9029a5feddebdc9e',
    messagingSenderId: '134055692731',
    projectId: 'learning-assistant-7b8e2',
    authDomain: 'learning-assistant-7b8e2.firebaseapp.com',
    storageBucket: 'learning-assistant-7b8e2.firebasestorage.app',
    measurementId: 'G-6BRF41RT4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nPQ7lqieMiXHFxkJNw0L6NdsbZ77MCM',
    appId: '1:134055692731:android:5d93e36d9b416b80ebdc9e',
    messagingSenderId: '134055692731',
    projectId: 'learning-assistant-7b8e2',
    storageBucket: 'learning-assistant-7b8e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlc3LGxAaUZ2R3GXprPzke94SpX9jRDiA',
    appId: '1:134055692731:ios:625e56551e1fbc15ebdc9e',
    messagingSenderId: '134055692731',
    projectId: 'learning-assistant-7b8e2',
    storageBucket: 'learning-assistant-7b8e2.firebasestorage.app',
    iosBundleId: 'com.example.learningAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlc3LGxAaUZ2R3GXprPzke94SpX9jRDiA',
    appId: '1:134055692731:ios:625e56551e1fbc15ebdc9e',
    messagingSenderId: '134055692731',
    projectId: 'learning-assistant-7b8e2',
    storageBucket: 'learning-assistant-7b8e2.firebasestorage.app',
    iosBundleId: 'com.example.learningAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0CBkl1pweSjq-wfSzudYazH84o0vnS6k',
    appId: '1:134055692731:web:75d9690d70414c95ebdc9e',
    messagingSenderId: '134055692731',
    projectId: 'learning-assistant-7b8e2',
    authDomain: 'learning-assistant-7b8e2.firebaseapp.com',
    storageBucket: 'learning-assistant-7b8e2.firebasestorage.app',
    measurementId: 'G-WYFQ8WKR7L',
  );
}
